# build environment
FROM node:lts-alpine as build
RUN mkdir /app
COPY . /app
WORKDIR /app
## ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
ENV REACT_APP_API_URL http://servelx.duckdns.org:3333
RUN yarn
RUN yarn build
COPY . /app

# production environment
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]

