version: '3.7'
services:
    app:
        container_name: web-gobarber
        build:
          context: .
          dockerfile: Dockerfile-prod-router
        volumes:
          - '.:/app'
          - '/app/node_modules'
        ports:
          - '3000:3000'
